import type { Currency } from '../types/currency'

export const currencies: Currency[] = [
    { currencyAcronym: 'AED', currencyName: 'United Arab Emirates Dirham', currencyFlag: 'ae' },
    { currencyAcronym: 'AFN', currencyName: 'Afghan Afghani', currencyFlag: 'af' },
    { currencyAcronym: 'ALL', currencyName: 'Albanian Lek', currencyFlag: 'al' },
    { currencyAcronym: 'AMD', currencyName: 'Armenian Dram', currencyFlag: 'am' },
    { currencyAcronym: 'ANG', currencyName: 'Netherlands Antillean Guilder', currencyFlag: 'cw' },
    { currencyAcronym: 'AOA', currencyName: 'Angolan Kwanza', currencyFlag: 'ao' },
    { currencyAcronym: 'ARS', currencyName: 'Argentine Peso', currencyFlag: 'ar' },
    { currencyAcronym: 'AUD', currencyName: 'Australian Dollar', currencyFlag: 'au' },
    { currencyAcronym: 'AWG', currencyName: 'Aruban Florin', currencyFlag: 'aw' },
    { currencyAcronym: 'AZN', currencyName: 'Azerbaijani Manat', currencyFlag: 'az' },
    { currencyAcronym: 'BAM', currencyName: 'Bosnia-Herzegovina Convertible Mark', currencyFlag: 'ba' },
    { currencyAcronym: 'BBD', currencyName: 'Barbadian Dollar', currencyFlag: 'bb' },
    { currencyAcronym: 'BDT', currencyName: 'Bangladeshi Taka', currencyFlag: 'bd' },
    { currencyAcronym: 'BGN', currencyName: 'Bulgarian Lev', currencyFlag: 'bg' },
    { currencyAcronym: 'BHD', currencyName: 'Bahraini Dinar', currencyFlag: 'bh' },
    { currencyAcronym: 'BIF', currencyName: 'Burundian Franc', currencyFlag: 'bi' },
    { currencyAcronym: 'BMD', currencyName: 'Bermudan Dollar', currencyFlag: 'bm' },
    { currencyAcronym: 'BND', currencyName: 'Brunei Dollar', currencyFlag: 'bn' },
    { currencyAcronym: 'BOB', currencyName: 'Bolivian Boliviano', currencyFlag: 'bo' },
    { currencyAcronym: 'BRL', currencyName: 'Brazilian Real', currencyFlag: 'br' },
    { currencyAcronym: 'BSD', currencyName: 'Bahamian Dollar', currencyFlag: 'bs' },
    { currencyAcronym: 'BTN', currencyName: 'Bhutanese Ngultrum', currencyFlag: 'bt' },
    { currencyAcronym: 'BWP', currencyName: 'Botswanan Pula', currencyFlag: 'bw' },
    { currencyAcronym: 'BYN', currencyName: 'New Belarusian Ruble', currencyFlag: 'by' },
    { currencyAcronym: 'BYR', currencyName: 'Belarusian Ruble', currencyFlag: 'by' },
    { currencyAcronym: 'BZD', currencyName: 'Belize Dollar', currencyFlag: 'bz' },
    { currencyAcronym: 'CAD', currencyName: 'Canadian Dollar', currencyFlag: 'ca' },
    { currencyAcronym: 'CDF', currencyName: 'Congolese Franc', currencyFlag: 'cd' },
    { currencyAcronym: 'CHF', currencyName: 'Swiss Franc', currencyFlag: 'ch' },
    { currencyAcronym: 'CLF', currencyName: 'Chilean Unit of Account (UF)', currencyFlag: 'cl' },
    { currencyAcronym: 'CLP', currencyName: 'Chilean Peso', currencyFlag: 'cl' },
    { currencyAcronym: 'CNY', currencyName: 'Chinese Yuan', currencyFlag: 'cn' },
    { currencyAcronym: 'CNH', currencyName: 'Chinese Yuan Offshore', currencyFlag: 'cn' },
    { currencyAcronym: 'COP', currencyName: 'Colombian Peso', currencyFlag: 'co' },
    { currencyAcronym: 'CRC', currencyName: 'Costa Rican Colón', currencyFlag: 'cr' },
    { currencyAcronym: 'CUC', currencyName: 'Cuban Convertible Peso', currencyFlag: 'cu' },
    { currencyAcronym: 'CUP', currencyName: 'Cuban Peso', currencyFlag: 'cu' },
    { currencyAcronym: 'CVE', currencyName: 'Cape Verdean Escudo', currencyFlag: 'cv' },
    { currencyAcronym: 'CZK', currencyName: 'Czech Republic Koruna', currencyFlag: 'cz' },
    { currencyAcronym: 'DJF', currencyName: 'Djiboutian Franc', currencyFlag: 'dj' },
    { currencyAcronym: 'DKK', currencyName: 'Danish Krone', currencyFlag: 'dk' },
    { currencyAcronym: 'DOP', currencyName: 'Dominican Peso', currencyFlag: 'do' },
    { currencyAcronym: 'DZD', currencyName: 'Algerian Dinar', currencyFlag: 'dz' },
    { currencyAcronym: 'EGP', currencyName: 'Egyptian Pound', currencyFlag: 'eg' },
    { currencyAcronym: 'ERN', currencyName: 'Eritrean Nakfa', currencyFlag: 'er' },
    { currencyAcronym: 'ETB', currencyName: 'Ethiopian Birr', currencyFlag: 'et' },
    { currencyAcronym: 'EUR', currencyName: 'Euro', currencyFlag: 'eu' },
    { currencyAcronym: 'FJD', currencyName: 'Fijian Dollar', currencyFlag: 'fj' },
    { currencyAcronym: 'FKP', currencyName: 'Falkland Islands Pound', currencyFlag: 'fk' },
    { currencyAcronym: 'GBP', currencyName: 'British Pound Sterling', currencyFlag: 'gb' },
    { currencyAcronym: 'GEL', currencyName: 'Georgian Lari', currencyFlag: 'ge' },
    { currencyAcronym: 'GGP', currencyName: 'Guernsey Pound', currencyFlag: 'gg' },
    { currencyAcronym: 'GHS', currencyName: 'Ghanaian Cedi', currencyFlag: 'gh' },
    { currencyAcronym: 'GIP', currencyName: 'Gibraltar Pound', currencyFlag: 'gi' },
    { currencyAcronym: 'GMD', currencyName: 'Gambian Dalasi', currencyFlag: 'gm' },
    { currencyAcronym: 'GNF', currencyName: 'Guinean Franc', currencyFlag: 'gn' },
    { currencyAcronym: 'GTQ', currencyName: 'Guatemalan Quetzal', currencyFlag: 'gt' },
    { currencyAcronym: 'GYD', currencyName: 'Guyanaese Dollar', currencyFlag: 'gy' },
    { currencyAcronym: 'HKD', currencyName: 'Hong Kong Dollar', currencyFlag: 'hk' },
    { currencyAcronym: 'HNL', currencyName: 'Honduran Lempira', currencyFlag: 'hn' },
    { currencyAcronym: 'HRK', currencyName: 'Croatian Kuna', currencyFlag: 'hr' },
    { currencyAcronym: 'HTG', currencyName: 'Haitian Gourde', currencyFlag: 'ht' },
    { currencyAcronym: 'HUF', currencyName: 'Hungarian Forint', currencyFlag: 'hu' },
    { currencyAcronym: 'IDR', currencyName: 'Indonesian Rupiah', currencyFlag: 'id' },
    { currencyAcronym: 'ILS', currencyName: 'Israeli New Sheqel', currencyFlag: 'il' },
    { currencyAcronym: 'IMP', currencyName: 'Manx pound', currencyFlag: 'im' },
    { currencyAcronym: 'INR', currencyName: 'Indian Rupee', currencyFlag: 'in' },
    { currencyAcronym: 'IQD', currencyName: 'Iraqi Dinar', currencyFlag: 'iq' },
    { currencyAcronym: 'IRR', currencyName: 'Iranian Rial', currencyFlag: 'ir' },
    { currencyAcronym: 'ISK', currencyName: 'Icelandic Króna', currencyFlag: 'is' },
    { currencyAcronym: 'JEP', currencyName: 'Jersey Pound', currencyFlag: 'je' },
    { currencyAcronym: 'JMD', currencyName: 'Jamaican Dollar', currencyFlag: 'jm' },
    { currencyAcronym: 'JOD', currencyName: 'Jordanian Dinar', currencyFlag: 'jo' },
    { currencyAcronym: 'JPY', currencyName: 'Japanese Yen', currencyFlag: 'jp' },
    { currencyAcronym: 'KES', currencyName: 'Kenyan Shilling', currencyFlag: 'ke' },
    { currencyAcronym: 'KGS', currencyName: 'Kyrgystani Som', currencyFlag: 'kg' },
    { currencyAcronym: 'KHR', currencyName: 'Cambodian Riel', currencyFlag: 'kh' },
    { currencyAcronym: 'KMF', currencyName: 'Comorian Franc', currencyFlag: 'km' },
    { currencyAcronym: 'KPW', currencyName: 'North Korean Won', currencyFlag: 'kp' },
    { currencyAcronym: 'KRW', currencyName: 'South Korean Won', currencyFlag: 'kr' },
    { currencyAcronym: 'KWD', currencyName: 'Kuwaiti Dinar', currencyFlag: 'kw' },
    { currencyAcronym: 'KYD', currencyName: 'Cayman Islands Dollar', currencyFlag: 'ky' },
    { currencyAcronym: 'KZT', currencyName: 'Kazakhstani Tenge', currencyFlag: 'kz' },
    { currencyAcronym: 'LAK', currencyName: 'Laotian Kip', currencyFlag: 'la' },
    { currencyAcronym: 'LBP', currencyName: 'Lebanese Pound', currencyFlag: 'lb' },
    { currencyAcronym: 'LKR', currencyName: 'Sri Lankan Rupee', currencyFlag: 'lk' },
    { currencyAcronym: 'LRD', currencyName: 'Liberian Dollar', currencyFlag: 'lr' },
    { currencyAcronym: 'LSL', currencyName: 'Lesotho Loti', currencyFlag: 'ls' },
    { currencyAcronym: 'LTL', currencyName: 'Lithuanian Litas', currencyFlag: 'lt' },
    { currencyAcronym: 'LVL', currencyName: 'Latvian Lats', currencyFlag: 'lv' },
    { currencyAcronym: 'LYD', currencyName: 'Libyan Dinar', currencyFlag: 'ly' },
    { currencyAcronym: 'MAD', currencyName: 'Moroccan Dirham', currencyFlag: 'ma' },
    { currencyAcronym: 'MDL', currencyName: 'Moldovan Leu', currencyFlag: 'md' },
    { currencyAcronym: 'MGA', currencyName: 'Malagasy Ariary', currencyFlag: 'mg' },
    { currencyAcronym: 'MKD', currencyName: 'Macedonian Denar', currencyFlag: 'mk' },
    { currencyAcronym: 'MMK', currencyName: 'Myanma Kyat', currencyFlag: 'mm' },
    { currencyAcronym: 'MNT', currencyName: 'Mongolian Tugrik', currencyFlag: 'mn' },
    { currencyAcronym: 'MOP', currencyName: 'Macanese Pataca', currencyFlag: 'mo' },
    { currencyAcronym: 'MRU', currencyName: 'Mauritanian Ouguiya', currencyFlag: 'mr' },
    { currencyAcronym: 'MUR', currencyName: 'Mauritian Rupee', currencyFlag: 'mu' },
    { currencyAcronym: 'MVR', currencyName: 'Maldivian Rufiyaa', currencyFlag: 'mv' },
    { currencyAcronym: 'MWK', currencyName: 'Malawian Kwacha', currencyFlag: 'mw' },
    { currencyAcronym: 'MXN', currencyName: 'Mexican Peso', currencyFlag: 'mx' },
    { currencyAcronym: 'MYR', currencyName: 'Malaysian Ringgit', currencyFlag: 'my' },
    { currencyAcronym: 'MZN', currencyName: 'Mozambican Metical', currencyFlag: 'mz' },
    { currencyAcronym: 'NAD', currencyName: 'Namibian Dollar', currencyFlag: 'na' },
    { currencyAcronym: 'NGN', currencyName: 'Nigerian Naira', currencyFlag: 'ng' },
    { currencyAcronym: 'NIO', currencyName: 'Nicaraguan Córdoba', currencyFlag: 'ni' },
    { currencyAcronym: 'NOK', currencyName: 'Norwegian Krone', currencyFlag: 'no' },
    { currencyAcronym: 'NPR', currencyName: 'Nepalese Rupee', currencyFlag: 'np' },
    { currencyAcronym: 'NZD', currencyName: 'New Zealand Dollar', currencyFlag: 'nz' },
    { currencyAcronym: 'OMR', currencyName: 'Omani Rial', currencyFlag: 'om' },
    { currencyAcronym: 'PAB', currencyName: 'Panamanian Balboa', currencyFlag: 'pa' },
    { currencyAcronym: 'PEN', currencyName: 'Peruvian Nuevo Sol', currencyFlag: 'pe' },
    { currencyAcronym: 'PGK', currencyName: 'Papua New Guinean Kina', currencyFlag: 'pg' },
    { currencyAcronym: 'PHP', currencyName: 'Philippine Peso', currencyFlag: 'ph' },
    { currencyAcronym: 'PKR', currencyName: 'Pakistani Rupee', currencyFlag: 'pk' },
    { currencyAcronym: 'PLN', currencyName: 'Polish Zloty', currencyFlag: 'pl' },
    { currencyAcronym: 'PYG', currencyName: 'Paraguayan Guarani', currencyFlag: 'py' },
    { currencyAcronym: 'QAR', currencyName: 'Qatari Rial', currencyFlag: 'qa' },
    { currencyAcronym: 'RON', currencyName: 'Romanian Leu', currencyFlag: 'ro' },
    { currencyAcronym: 'RSD', currencyName: 'Serbian Dinar', currencyFlag: 'rs' },
    { currencyAcronym: 'RUB', currencyName: 'Russian Ruble', currencyFlag: 'ru' },
    { currencyAcronym: 'RWF', currencyName: 'Rwandan Franc', currencyFlag: 'rw' },
    { currencyAcronym: 'SAR', currencyName: 'Saudi Riyal', currencyFlag: 'sa' },
    { currencyAcronym: 'SBD', currencyName: 'Solomon Islands Dollar', currencyFlag: 'sb' },
    { currencyAcronym: 'SCR', currencyName: 'Seychellois Rupee', currencyFlag: 'sc' },
    { currencyAcronym: 'SDG', currencyName: 'South Sudanese Pound', currencyFlag: 'sd' },
    { currencyAcronym: 'SEK', currencyName: 'Swedish Krona', currencyFlag: 'se' },
    { currencyAcronym: 'SGD', currencyName: 'Singapore Dollar', currencyFlag: 'sg' },
    { currencyAcronym: 'SHP', currencyName: 'Saint Helena Pound', currencyFlag: 'sh' },
    { currencyAcronym: 'SLE', currencyName: 'Sierra Leonean Leone', currencyFlag: 'sl' },
    { currencyAcronym: 'SLL', currencyName: 'Sierra Leonean Leone', currencyFlag: 'sl' },
    { currencyAcronym: 'SOS', currencyName: 'Somali Shilling', currencyFlag: 'so' },
    { currencyAcronym: 'SRD', currencyName: 'Surinamese Dollar', currencyFlag: 'sr' },
    { currencyAcronym: 'STD', currencyName: 'São Tomé and Príncipe Dobra', currencyFlag: 'st' },
    { currencyAcronym: 'STN', currencyName: 'São Tomé and Príncipe Dobra', currencyFlag: 'st' },
    { currencyAcronym: 'SVC', currencyName: 'Salvadoran Colón', currencyFlag: 'sv' },
    { currencyAcronym: 'SYP', currencyName: 'Syrian Pound', currencyFlag: 'sy' },
    { currencyAcronym: 'SZL', currencyName: 'Swazi Lilangeni', currencyFlag: 'sz' },
    { currencyAcronym: 'THB', currencyName: 'Thai Baht', currencyFlag: 'th' },
    { currencyAcronym: 'TJS', currencyName: 'Tajikistani Somoni', currencyFlag: 'tj' },
    { currencyAcronym: 'TMT', currencyName: 'Turkmenistani Manat', currencyFlag: 'tm' },
    { currencyAcronym: 'TND', currencyName: 'Tunisian Dinar', currencyFlag: 'tn' },
    { currencyAcronym: 'TOP', currencyName: 'Tongan Paʻanga', currencyFlag: 'to' },
    { currencyAcronym: 'TRY', currencyName: 'Turkish Lira', currencyFlag: 'tr' },
    { currencyAcronym: 'TTD', currencyName: 'Trinidad and Tobago Dollar', currencyFlag: 'tt' },
    { currencyAcronym: 'TWD', currencyName: 'New Taiwan Dollar', currencyFlag: 'tw' },
    { currencyAcronym: 'TZS', currencyName: 'Tanzanian Shilling', currencyFlag: 'tz' },
    { currencyAcronym: 'UAH', currencyName: 'Ukrainian Hryvnia', currencyFlag: 'ua' },
    { currencyAcronym: 'UGX', currencyName: 'Ugandan Shilling', currencyFlag: 'ug' },
    { currencyAcronym: 'USD', currencyName: 'United States Dollar', currencyFlag: 'us' },
    { currencyAcronym: 'UYU', currencyName: 'Uruguayan Peso', currencyFlag: 'uy' },
    { currencyAcronym: 'UZS', currencyName: 'Uzbekistan Som', currencyFlag: 'uz' },
    { currencyAcronym: 'VES', currencyName: 'Sovereign Bolivar', currencyFlag: 've' },
    { currencyAcronym: 'VND', currencyName: 'Vietnamese Dong', currencyFlag: 'vn' },
    { currencyAcronym: 'VUV', currencyName: 'Vanuatu Vatu', currencyFlag: 'vu' },
    { currencyAcronym: 'WST', currencyName: 'Samoan Tala', currencyFlag: 'ws' },
    { currencyAcronym: 'YER', currencyName: 'Yemeni Rial', currencyFlag: 'ye' },
    { currencyAcronym: 'ZAR', currencyName: 'South African Rand', currencyFlag: 'za' },
    { currencyAcronym: 'ZMK', currencyName: 'Zambian Kwacha (pre-2013)', currencyFlag: 'zm' },
    { currencyAcronym: 'ZMW', currencyName: 'Zambian Kwacha', currencyFlag: 'zm' },
    { currencyAcronym: 'ZWL', currencyName: 'Zimbabwean Dollar', currencyFlag: 'zw' }
]
